{
 "title": "Gravity Operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gravity_operator_cluster_status{status=\"available\"}",
     "legendFormat": "available"
    },
    {
     "expr": "gravity_operator_cluster_status{status=\"unavailable\"}",
     "legendFormat": "unavailable"
    },
    {
     "expr": "gravity_operator_cluster_status{status=\"total\"}",
     "legendFormat": "total"
    },
    {
     "expr": "gravity_operator_cluster_status{status=\"updated\"}",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Unavailable Pipeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gravity_operator_pipeline_unavailable",
     "legendFormat": "{{ pipeline}}"
    }
   ]
  },
  {
   "title": "Sync Success Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gravity_operator_sync_counter{controller=\"cluster\", result=\"success\"}[1m])",
     "legendFormat": "cluster"
    },
    {
     "expr": "increase(gravity_operator_sync_counter{controller=\"pipeline\", result=\"success\"}[1m])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Sync Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gravity_operator_sync_counter{controller=\"cluster\", result=\"error\"}[5m])",
     "legendFormat": "cluster"
    },
    {
     "expr": "increase(gravity_operator_sync_counter{controller=\"pipeline\", result=\"error\"}[5m])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Sync Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(gravity_operator_schedule_duration_seconds_bucket[1m])) by (le, pipeline))",
     "legendFormat": "{{ pipeline}}"
    }
   ]
  }
 ]
}